project:
  type: website
  resources:
    - "/newsletter/**"

website:
  title: "IBS-AR"
  favicon: favicon.ico
  repo-url: https://github.com/IBS-AR/IBS-AR.github.io
  repo-actions: [edit, issue]
  sidebar:
    logo: logo-ibs-ar.svg
  navbar:
    logo: logo-ibs-ar.svg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - council.qmd
      - news.qmd
      - awards.qmd
      - conferences.qmd
      - membership.qmd
      - contact.qmd
    tools:
      - icon: github
        url: https://github.com/IBS-AR/IBS-AR.github.io



format:
  html:
    theme: [flatly, ibs-theme.scss]
    css: styles.css
    toc: true



